### ISSUE TITLE
Failure of metadata retrieval behind enterprise proxy

### ISSUE THREAD

**Issue by vico** [factset/enterprise-sdk-utils-python#23]
**Is your feature request related to a problem? Please describe.**
I tried to use Universal Screening API behind an enterprise proxy, and the sample code failed at the following line:

https://github.com/factset/enterprise-sdk-utils-python/blob/main/src/fds/sdk/utils/authentication/confidential.py#L130

**Describe the solution you'd like**
I see the proxy information can be set via 

https://github.com/factset/enterprise-sdk/blob/8a2d02528b0ba45a7822ebe4b43a07c759b18306/code/python/UniversalScreening/v2/fds/sdk/UniversalScreening/configuration.py#L199

so it is nice if the proxy setting can be passed to `fds/sdk/utils/authentication/confidential.py`

**Describe alternatives you've considered**
Otherwise, I would love to have a way for the library can read proxy information from a Yaml file or a text file. 
The path to this setting file can be optionally passed to the initialization of `fds.sdk.UniversalScreening.Configuration` or
the proxy information can be given via parameters. And other APIs share the same proxy setting file.

**Additional context**
Some enterprise proxies do authorize based on User-agent (only browsers can get through), so it is nice to be able to set headers information just for proxy authentication.

**Comment by eschmidtfds** [comment]
Hi @vico,

thanks for filing this issue!
The ConfidentialClient should somehow support this as well. We'll discuss internally how to add this to the config of the ConfidentialClient class. Thanks for the ideas!

You probably found this already:
A potential workaround for now might be setting the environment variable `HTTPS_PROXY` to the url of your proxy.
The [`requests` library](https://requests.readthedocs.io/en/latest/user/advanced/#proxies) picks it up from there. The docs also have some more info regarding ssl certs in case your proxy uses a self-signed one.
Note: This works only for the ConfidentialClient class, the SDK needs the proxy settings as you found out.

Example:
```py
from fds.sdk.utils.authentication import ConfidentialClient
import fds.sdk.UniversalScreening
import os

proxy = "http://proxy_ip:port"
ca_cert = "/path/to/proxies_cert_or_bundle_with_the_cert.pem"

# for the ConfidentialClient
os.environ['HTTPS_PROXY'] = proxy
os.environ['REQUESTS_CA_BUNDLE'] = ca_cert # only needed if the proxy uses a self-signed certificate

client = ConfidentialClient('/path/to/app-config.json')
print(client.get_access_token())

# for the SDK configuration
configuration = fds.sdk.UniversalScreening.Configuration(
    fds_oauth_client=client
)
configuration.proxy = proxy
configuration.ssl_ca_cert = ca_cert # only needed if the proxy uses a self-signed certificate

# ...
```

Let me know if that works for you for the moment!

**Comment by vico** [comment]
Hi @eschmidtfds ,

Thank you for your help!
It is hard for me to get a proxy's certificate, so I usually need to specify `verify=False` in `requests`.
For this reason, I tried the above code and got an `SSLCertVerificationError`.

After making some modifications to `fds.sdk.utils.authentication.confidential.py`  I got my code run successfully now, and this issue is not urgent.


For your information, I updated the following methods to make `verify=False` and specify the `proxies`, and include necessary HTTP headers :
1. `_init_auth_server_metadata`  
2. `get_access_token`

One final issue I encountered is the authentication information of the proxy is not passed to subsequent requests.
So I need to manually specify the `Proxy-Authorization` header in the API request to get the data.
Usually, all the requests can be included in one `requests.Session()` and that help propagate the authentication information through all the requests, but I do not know how to do it with the API.

**Comment by eschmidtfds** [comment]
Ah, I see.
I'm sure you tried this already, but just in case, some ieas: Your proxy might send its CA cert along, in which case you can try grabbing it via the browser or the openssl command line utility. Or if proxied requests work without a problem in your browser, maybe you can export it from there.

But in any event, our OAuth lib needs those settings.

Re: `Proxy-Authorization` this is still for the ConfidentialClient class, correct? Would you mind sharing a redacted code example of one of the two methods you had to edit?

I think you can supply the proxy auth via the proxy url (http://user:pw@proxy:port) for the ConfidentialClient.
But since you have to disable ssl verification anyway by editing the code, I guess you might as well add the headers there for now.

How are you adding the proxy auth to the SDK right now?
The SDK has options to disable verification and to specify extra headers: Configiuration.verify_ssl, Configuration.proxy_headers, and/or ApiClient.default_headers.

I'll add the authentication piece to our work item.
